### ISSUE TITLE
feat: Containerized task runner

### ISSUE THREAD

**Issue by mumoshu** [mumoshu/variant#10]
As a developer who wants to ease dependency management of my variant tasks, I'd like to use docker containers to run the tasks:

```yaml
# flows:
onchange:
  parameters:
  - name: changed-files
    type: array
    delimiter: newline
  steps:
  -  items: changed-files
      filter: { "path.match": "playbooks/*.yml" }
      flow: run-ansible-playbook
      arguments:
        playbook: '{{ .item | replace "playbooks/" "" }}'
run-ansible-playbook:
  parameters:
  - name: playbook
  script: |
    ansible-playbook -i hosts/myhosts playbooks/{{ get "playbook" }}.yml -K
  container:
    image: mumoshu/my-ansible-image:dev
    command: bash
    args: [-c]
```

And you containerize it like:

```
variant --set run-ansible-playbook.runner=docker onchange --changed-files "$(cat changed-files)"
```

In case you want to carry the local context to the container, use a docker build context by:

```
variant --set run-ansible-playbook.runner=dockerbuilder onchange --changed-files "$(cat changed-files)"
```

Or should I automatically create a tarball of the local context and somehow send it to the container? Probably something like `tar czvf ./ | docker run myimage bash -c "tar zxvf && ./variantfile --changed-files $changed_files"`?

Edit: I'd rather go with the tarball way to pass contexts. The rationale is that the possibility to use the same semantic to support the context passing in #12.

```yaml
run-ansible-playbook:
  parameters:
  - name: playbook
  script: |
    ansible-playbook -i hosts/myhosts playbooks/{{ get "playbook" }}.yml -K
  # The default runner. Can be overrode via `--set run-ansible-playbook.runner=codebuild`
  #runner: localexec
  runners:
    localexec: {}
    docker: &docker
      container:
        image: mumoshu/my-ansible-image:dev
      command: bash
      args: [-c]
      bundle:
        # this is the default config
        # include: '*' 
        ignore:
        - *~
        - dist/
        # or `include: ["playbooks", "hosts", "roles"]` to override `include: *`
    codebuild:
      <<: *docker
      github: default/to/url/of/git/origin
      ref: default/to/head/sha1
      # the below cmd is prepended before the command + args + script
      # `aws s3 cp s3://mybucket/path/to/{{ get "task.id" }}.tgz bundle.tgz && tar zxvf bundle.tgz`
      bundle-s3uri: 's3://mybucket/path/to/{{ get "task.id" }}.tgz'
```
