### ISSUE TITLE
Feature: Allow direct binding (without prefixes) of the environment variables to the task parameters

### ISSUE THREAD

**Issue by aroq** [mumoshu/variant#103]
## what
Allow direct binding (without prefixes) of the environment variables to the task parameters.
```bind_env_vars``` parameter would be used to set the direct binding mode for the chosen tasks.

## why
It will allow us to pass the parameters for the chosen tasks in a more transparent way (environment variable name would be always the same both for ```variant``` and for the applications wrapped by ```variant```).

You can think about it as:

```PARAM1="OK" variant test``` vs ```VARIANT_FLAGS_TEST_PARAM1="OK" variant test```

The following task would output "OK" when called as ```PARAM1="OK" variant test```:

```yaml
tasks:
  test:
    bind_env_vars: true
    parameters:
    - name: PARAM1
      default: ""
    script: echo "${PARAM1}"
```
