### ISSUE TITLE
feat: Introduce config contexts and config directories parameters

### ISSUE THREAD

**Issue by aroq** [mumoshu/variant#113]
## what
- Introduce `--config-context` parameter to set configuration contexts.
- Introduce `--config-directory `parameter to set configuration directories.
- The values can be comma-separated in case of using environment variables (see the example below).
- Variant command file location dir & working dir are always included to configuration directories list by default.
- The current variant command name is always included in the list of contexts.

## why
- This change will make the configuration process more flexible
- It will eliminate redundant `env set` command and whole 'environment' concept which is too specific for the general-purpose tool such as `variant`. 

---

### Command example
```
VARIANT_CONFIG_CONTEXT="cluster1,dev" VARIANT_CONFIG_DIR="test,config/environments" VARIANT_LOG_LEVEL="info" tools/sync/sync {cmd}
```

### Loaded configuration files for the above command
As you can see, variant builds the list of possible configuration files based on contexts and seaches for these files in the config directories:

```
...
loading config file tools/sync/sync.yaml... done
loading config file tools/sync/cluster1.yaml... missing
loading config file tools/sync/dev.yaml... done
loading config file tools/sync/sync.cluster1.yaml... missing
loading config file tools/sync/sync.dev.yaml... done
loading config file tools/sync/sync.cluster1.dev.yaml... missing
loading config file tools/sync/cluster1.dev.yaml... missing
loading config file sync.yaml... done
loading config file cluster1.yaml... missing
loading config file dev.yaml... done
loading config file sync.cluster1.yaml... missing
loading config file sync.dev.yaml... done
loading config file sync.cluster1.dev.yaml... missing
loading config file cluster1.dev.yaml... missing
loading config file test/sync.yaml... missing
loading config file test/cluster1.yaml... missing
loading config file test/dev.yaml... missing
loading config file test/sync.cluster1.yaml... missing
loading config file test/sync.dev.yaml... missing
loading config file test/sync.cluster1.dev.yaml... missing
loading config file test/cluster1.dev.yaml... missing
loading config file config/environments/sync.yaml... missing
loading config file config/environments/cluster1.yaml... missing
loading config file config/environments/dev.yaml... done
loading config file config/environments/sync.cluster1.yaml... missing
loading config file config/environments/sync.dev.yaml... missing
loading config file config/environments/sync.cluster1.dev.yaml... missing
loading config file config/environments/cluster1.dev.yaml... missing
...
```

Related issue: https://github.com/mumoshu/variant/issues/65

**Comment by mumoshu** [comment]
@aroq Thanks! I'm still trying to understand how this works.

Can I safely say that the above example is an equivalent of `{$VARIANT_CMD_DIR,.,test,config/environments}/{$VARIANT_CMD_BASENAME,cluster1,dev}` in shell expansion, where if `$VARIANT_CMD_DIR` translated to the directory where the command `tools/sync/sync` is in - `tools/sync`?

**Comment by mumoshu** [comment]
Also, can we configure this from within the variantfile a.k.a the yaml file containing the variant command definition?

**Comment by aroq** [comment]
> @aroq Thanks! I'm still trying to understand how this works.
> 
> Can I safely say that the above example is an equivalent of `{$VARIANT_CMD_DIR,.,test,config/environments}/{$VARIANT_CMD_BASENAME,cluster1,dev}` in shell expansion, where if `$VARIANT_CMD_DIR` translated to the directory where the command `tools/sync/sync` is in - `tools/sync`?

I don't believe that `config-context` could be defined by the shell expansion logic, as you can see, some config file name suggestions are combined from several components, like `sync.cluster1.dev.yaml`

You can see the actual implementation here (`config-context` is handled differently compared to `config-dir`): https://github.com/mumoshu/variant/pull/114/files#diff-303a352a0cc75622f50aa2c8b979d516R98

**Comment by aroq** [comment]
> Also, can we configure this from within the variantfile a.k.a the yaml file containing the variant command definition?

For me, it should be configured outside of `Variantfile`, as the same `Variantfile` could be executed with different contexts.

**Comment by mumoshu** [comment]
> For me, it should be configured outside of Variantfile

This seems to imply that we now need an another wrapper around Variant to use the command without knowing how many kinds of `context` the Variant command needs.

That said, it would be great if we can include it in the variant command definition like this:

```yaml
parameters:
- name: env
   type: string
- name: cluster
   type: string

config:
  contexts:
   - '{{.cluster}}'
    - {{ .env }}'
  directories:
  - test
  - config/environments

tasks:
- ...
```

**Comment by mumoshu** [comment]
> I don't believe that config-context could be defined by the shell expansion logic, as you can see, some config file name suggestions are combined from several components, like sync.cluster1.dev.yaml

Got it :)

**Comment by mumoshu** [comment]
I think this should be more configurable. Do you think we can make search under the directory where the command itself resides - `tools/sync/` - configurable?

It will need to expose the directory in which your command resides via go template, like:

```
config:
  contexts:
   - '{{.cluster}}' #=> Replaced to the value provided via --cluster flag, like --cluster cluster1
    - '{{ .env }}' #=> Replaced to the value provided via --env flag like --env env1
  directories:
  - '{{ .variantCmdDir }}'
  - .
  - test
  - config/environments
```

**Comment by mumoshu** [comment]
The same can be said on contexts. Can we expose the base name of the command via `'{{ .variantCmdBase }}` so that contexts and directories are fully configurable:

```
config:
  contexts:
   - '{{ .variantCmdBase }}' #=> Replaced to "sync"
   - '{{.cluster}}' #=> Replaced to the value provided via --cluster flag, like --cluster cluster1
    - '{{ .env }}' #=> Replaced to the value provided via --env flag like --env env1
  directories:
  - '{{ .variantCmdDir }}' #=> Replaced to tools/sync
  - . #=> PWD
  - test
  - config/environments
```

**Comment by aroq** [comment]
> This seems to imply that we now need an another wrapper around Variant to enable using the command without knowing how many kinds of `context` the Variant command needs.
> 
> That said, it would be great if we can include it in the variant command definition like this:
> 
> ```yaml
> parameters:
> - name: env
>    type: string
>    required: true
> - name: cluster
>    type: string
>    required: true
> 
> config:
>   contexts:
>    - '{{.cluster}}' #=> Replaced to the value provided via --cluster flag, like --cluster cluster1
>     - '{{ .env }}' #=> Replaced to the value provided via --env flag like --env env1
>   directories:
>   - test
>   - config/environments

As for me, it would introduce the chicken-egg (🐔 🥚) problem and cause misunderstandings:
- we use config files (🐔) to provide parameter values (🥚)
- to use some parameter (🥚) we need to process the config file (🐔)  first

In your suggestion, you want to introduce new parameters (🥚: env, cluster) before processing config files (🐔) and that is not how variant works now (as I believe :) ).

Also, my idea was that Variantfile should not define the config contexts and config directories. It should only consume parameters from the provided files (suggested by dir & context combinations defined by default and passed externally).

Default values for confix contexts and config dirs should be enough for most of the cases, and for cases, where additional contexts are needed the caller is in charge of passing the right context and directory (if needed).

Now we use ```variant env set dev``` to set the "environment" context. In this case, we just let variant know which config file to load (and we pass it externally to the variant, so it's OK to pass other contexts externally as well).

The "environment" concept does not have any value by itself, it's just one of the possible contexts and idea was to replace one specific "environment" context by the opportunity to pass any context(s) externally and to be able to configure config directories externally as well.

In my opinion, according to the current logic, Variantfile itself should be separated from configuration other than default and be able to consume any config files passed to it (through config contexts & dirs). It shouldn't define contexts or config directories, by itself, but should be able to consume them when passed externally.

**Comment by mumoshu** [comment]
> In your suggestion, you want to introduce new parameters (🥚: env, cluster) before processing config files (🐔) and that is not how variant works now (as I believe :) ).

Good point! That makes sense a lot.

> The "environment" concept does not have any value by itself, it's just one of the possible contexts and idea was to replace one specific "environment" context by the opportunity to pass any context(s) externally and to be able to configure config directories externally as well.

Agreed.

> It shouldn't define contexts or config directories, by itself, but should be able to consume them when passed externally.

I basically agree. So I'm inclined to merge your work as-is now.

I'd still wish Variant could "optionally" support defining contexts or config directories by itself to implement "conventions" though.

I'd like Variant to be the only "wrapper" thing you need (in most cases).

When your Variant command has a convention like:

> "we have `cluster` and `environment` contexts that MUST be provided in order to make this command work",

I "prefer":

> `variant --cluster cluster1 --environment env1 whatevercmd`

over

> `VARIANT_CONFIG_CONTEXT=clulster1,env1 variant whatevercmd`

because the former has possibility to provide a rich error message like

> Missing --cluster. You need both --cluster and --environment set and --environment takes on of "prod", "staging", "dev".

`VARIANT_CONFIG_CONTEXT=clulster1,env1 variant whatevercmd` would be GREAT for a general-purpose tool because it is very common to add our own "conventions" on top of a general-purpose tool to help on-boarding and maintenance problems. I see this in Helm and Helmfile for example. That is, Helmfile just adds declarative, conventional configuration to Helm.

On the other hand,  `variant --cluster cluster1 --environment env1 whatevercmd` would be probably better for proprietary tools. An example of this is that I do have a Variant command that wraps `eksctl` and `helmfile` with config contexts of "environment" and "cluster" in one of the companies I work for. In the company the convention is fixed and I have no necessity to inject additional contexts, hence a list of possible contexts defined within the variant command itself makes sense.

**Comment by mumoshu** [comment]
Due to the fundamental issue about how variant processes parameters, a configuration should look something like the below:

```
config:
  parameters:
  - name: env
     type: string
     required: true
  - name: cluster
     type: string
     required: true
  contexts:
   - '{{.cluster}}' #=> Replaced to the value provided via --cluster flag, like --cluster cluster1
    - '{{ .env }}' #=> Replaced to the value provided via --env flag like --env env1
  directories:
  - test
  - config/environments
```

Here, `config.parameters` and a different kind of `parameters` that is used mostly for templating `contexts` and `directories`. `config.parameters` and loaded before config contexts, directories, and normal `parameters` so there's no chicken-and-egg problem(I hope so!

This will be an advanced feature that people use when and only when you're writing a tool that requires conventional config contexts/directories.
