### ISSUE TITLE
Commands description.

### ISSUE THREAD

**Issue by fforloff** [mumoshu/variant#117]
It would be good to be able to provide description to the commands, similar to the build-in "Help about any command", i.e.

`Usage:
  my app [command]

Available Commands:
  configure   Configure it
  deploy      Deploy it
  destroy     Destroy it   
  help        Help about any command`

**Comment by mumoshu** [comment]
@fforloff Hey!

Variant has `description`:

```yaml
tasks:
  app:
    description: "description of app here"
    script: echo
    tasks:
      deploy:
        description: "Deploy it"
        script: echo
      destroy:
        description: "Destroy it"
        script: echo
```

It does add `-h` that instructs Variant to print the help for the sub-command:

```
$ variant app -h
description of app here

Usage:
  variant app  [flags]
  variant app [command]

Available Commands:
  deploy      Deploy it
  destroy     Destroy it

Flags:
  -h, --help   help for app

Global Flags:
  -C, --color                        Colorize output (default true)
  -x, --config-context stringArray   Config context
  -d, --config-dir stringArray       Config dir
  -c, --config-file string           Path to config file
      --log-color-debug string       Log message color: debug (default "dark_gray")
      --log-color-error string       Log message color: error (default "red")
      --log-color-fatal string       Log message color: fatal (default "red")
      --log-color-info string        Log message color: info (default "cyan")
      --log-color-panic string       Log message color: panic (default "red")
      --log-color-trace string       Log message color: trace (default "dark_gray")
      --log-color-warn string        Log message color: warn (default "red")
      --log-level string             Log level. One of: panic|fatal|error|warn|info|debug|trace (default "info")
      --logtostderr                  write log messages to stderr (default true)
  -o, --output string                Output format. One of: json|text|bunyan (default "text")
  -v, --verbose                      verbose output

Use "variant app [command] --help" for more information about a command.
```

Is this what you're looking for? Should it be `variant app help` exactly?

Any feedback is welcomed. Thanks for trying Variant!
