### ISSUE TITLE
feat: AWS CodeBuild runner

### ISSUE THREAD

**Issue by mumoshu** [mumoshu/variant#12]
As an extension to #10, I'd like to run any variant task as a AWS CodeBuild build.

That is, the example variant task below:

```yaml
tasks:
  run:
     parameters:
     - name: param1
     options:
     - name: opt1
     steps:
     - script: |
       echo foobar
     - task: anothertask
       arguments:
         foo: bar
```

can be run as a AWS CodeBuild build by:

```console
variant --set run.runner=codebuild run myparam1 --opt1 myopt1
```

The command is transformed to a CodeBuild spec like:

```yaml
version: 0.2
  
phases:
  run:
    commands:
      - aws s3 s3://mybucket/path/to/localcontext.tgz ./ && tar zxvf localcontext.tgz
      - ./variantfile run myparam1 --opt1 myopt1 2> stderr.log 1> stdout.log
      - aws s3 stderr.log s3://mybucket/path/to/stderr.log
      - aws s3 stdout.log s3://mybucket/path/to/stdout.log
```

And then run like this under the hood:

```
tar czvf ./ > localcontext.tgz

aws s3 localcontext.tgz s3://mybucket/path/to/localcontext.tgz

# A stock variant docker image, or the image specified via `container.image` would be used to run the variant, aws s3, and tar commands
aws codebuild create-project --cli-input-json file://create-project.json
aws codebuild start-build --cli-input-json file://start-build.json

aws codebuild batch-get-builds --ids ids

# wait until it finishes and then...

aws s3 s3://mybucket/path/to/stderr.log stderr.log
cat stderr.log 1>&2
aws s3 s3://mybucket/path/to/stdout.log stdout.log
cat stdout.log
```

**Comment by mumoshu** [comment]
Realized that #10 and makes it possible to inject any runner as a docker image as long as it takes the `script` as the first argument.

So, I believe that we can implement something like this without enhancing variant itself:

```yaml
runner:
  image: mumoshu/variant-runner-codebuild:dev
  command: /run-in-codebuild
  args:
  - sh
  - -c
script: |
  echo hello
```
