### ISSUE TITLE
if & then statements don't work correctly. Task placed under then executed in any case

### ISSUE THREAD

**Issue by zestagio** [mumoshu/variant#121]
Hello,

Today I updated `variant` to the latest version and I faced with a problem that tasks placed inside `then` statement executed in any case. Just for example I created simple file:

```yaml
#!/usr/bin/env var

tasks:
  ok:
    steps:
      - if:
          - task: success
        then:
          - task: foo

  success:
    script: echo false; exit 1
  foo:
    script: echo foo
```
and result is:
```
variant do ok
do ≫ starting task success
false
do.success ≫ script step failed: exit status 1
exit status was 1
do ≫ starting task foo
foo
```

it is reproducable since this release https://github.com/mumoshu/variant/releases/tag/v0.30.0

**Comment by mumoshu** [comment]
@zestagio Thanks again for your detailed report!

I've fixed it in https://github.com/mumoshu/variant/commit/7e70ed4aa36350543c65cd4d0df7e6f51d034118 and released it as v0.33.2.

Would you mind confirming?

**Comment by zestagio** [comment]
Hello @mumoshu 

Initial problem was fixed, but it seems I found another one bug (I'm not sure):

```yaml
#!/usr/bin/env var

tasks:
  ok:
    steps:
      - if:
          - task: success
        then:
          - task: foo
      - task: bar

  success:
    script: echo false; exit 1
  foo:
    script: echo foo
  bar:
    script: echo bar
```

```
variant do ok
do ≫ starting task success
false
do.success ≫ script step failed: exit status 1
exit status was 1
Error: `do ok` failed: do failed running task ok
Task#Run failed while running a script
`if` step failed
failed running step
do failed running task success
Task#Run failed while running a script
script step failed
exit status 1
Caused by: if step failed
```

As we can see a `bar` task is outside of `if` statement, but it's not executed. As for me I'm expecting the `bar` task should be executed any case
