### ISSUE TITLE
Question: how to keep the script sections DRY?

### ISSUE THREAD

**Issue by fforloff** [mumoshu/variant#123]
Suppose I have the following tasks - diff, apply, destroy, which essentially run the same set of script commands - apart from one argument (the actual action), and the "are you sure?" block in the "destroy".
So currently I copy/paste scripts between the tasks. Is there a better way?

**Comment by mumoshu** [comment]
@fforloff Hey! Sorry for the long silence. I'd recommend using YAML anchors to reuse snippets:

```yaml
snippets:
  lib: | &lib
    foo() {
      echo do whatever
    }

tasks:
  doit:
    script:
    - *lib
    - |
      # as all the array items under `script` is merged into a single (bash) script, you can call `foo`
      foo
```
