### ISSUE TITLE
Introduce v1 syntax

### ISSUE THREAD

**Issue by mumoshu** [mumoshu/variant#126]
I'd like to introduce the next generation of Variant's configuration syntax with a few additional features, which is basically an extension over #125.

- Rename `task` to `command`, as it's for literally definiting commands.
- Use `workflow` to run a DAG-represented workflow of `jobs` as described in #125
- Integrate with [variantdev/mod](https://github.com/variantdev/mod) for automatic dependency management, including retrieving latest version numbers of dependencies and install binaries and generate files based on the numbers, including Dockerfile and executables.
- Integrate with https://github.com/variantdev/vals
- Configure config contexts/directories(#113) from within the config file 
- Avoid deep nesting of `tasks`. Instead of `tasks.foo.tasks.bar.tasks.baz` to define `variant foo bar baz`, use `commands."foo bar baz"`

```yaml
apiVersion: v1

# See https://github.com/mumoshu/variant/issues/113
config:
  # Load `{{.Config.Values}}` from foo.yaml and bar.yaml.
  # Use contexts and directories instead for layering
  files:
  - foo.yaml
  - bar.yaml
  contexts:
  - cluster1,dev
  directories:
  - test
  - config/environments
  # This allows you to define default values
  values:
  - foo: bar
  # Supports https://github.com/variantdev/vals refs
  - ref+vault://mykv/mydoc#/myfield

# variantdev/mod dependencies.
# Dependencies are automatically loaded from `variant.lock`.
# If variant.lock is missing, it will automatically retrieve the latest version numbers and creates `variant.lock` from it.
# When variant.lock exists, you can manually run /variant mod build [--pull-request] to (re)generate and optionally submit a pr
dependencies:
  helmfile:
    releasesFrom:
      dockerImageTags:
        source: quay.io/roboll/helmfile
    version: "> 0.94.0"

# vavriantdev/mod provisioners.
provisioners:
  # If the target file is missing, variant will automatically create the file
  # You can manually run /variant mod build --pull-request to (re)generate and optionally submit a pr
  regexpReplace:
    Dockerfile:
      from: "(FROM helmfile:)(\\S+)(\\s+)"
      to: "${1}{{.Dependencies.helmfile.version}}${3}"
  executables:
    # Adds alias dockergo='docker run golang:{{.version}}' to $PATH
    dockergo:
      platforms:
        # Adds $VARIANT_MOD_PATH/mod/cache/CACHE_KEY/dockergo to $PATH
        # Or its shim at $VARIANT_MOD_PATH/MODULE_NAME/shims
      - docker:
          command: go
          image: golang
          tag: '{{.version}}'
          volume:
          - $PWD:/work
          workdir: /work

commands:
  hello:
    script: |
      echo hello
  app deploy:
    workflow:
      app1-enabled:
        type: bool
      app1-dir:
        type: string
        from:
        - env
        - config
        - script: somescript
          runner:
             image: foobar:tag
             command: somecmd
             args: [arg1]
      app1:
        command: {kubectl-apply: {file: "{{ .app1Dir }}"}}
        condition: .app1Enabled
        needs: [app1-enabled, app1-dir]
        #after: [parma1] if you don't refer to `.Deps.param1` from the template and only want to control execution order, not the existence of param1
      app2:
        task: {helm-upgrade: {chart: charts/mychart}}
```

TODOs:

- Implement Variant GitHub Action 
- In addition to triggering commands via slash commands on github issues/ps, add support for triggering via issue creation(any /slashcmd contained in the issue body are triggered)
