### ISSUE TITLE
feat: Testing framework

### ISSUE THREAD

**Issue by mumoshu** [mumoshu/variant#127]
I'd like to add a test runner and a testing framework for writing unit/integration tests for your variant commands.

The idea is you run `variant test` to run tests declared in a `variant-tests.yaml`:

```
testcases:
- name: test foo
   command: foo
   arguments:
     arg1: val1
   assert:
      contains: fooresult
   mock:
     binaries:
     - name: kubectl
        expect:
        - arguments: -n foo get po
          return: <pod yaml>             
```
