### ISSUE TITLE
feat: Slack integration

### ISSUE THREAD

**Issue by mumoshu** [mumoshu/variant#28]
One of goals of variant is becoming a next-gen task runner that supports our real lives.

Slack has become our defuct standard chat service that is used across your organization. I bet you have several Slack bots that supports your repetitive workflows. Dedicated SaaS, hubot, probot would be used for implementing bots. Now how do you want to shell-out from your bots, like executing variant tasks from bots via slash commands?

The idea is that you define, for example, a variant task named `deploy` in your variant task definition file, that is then somehow runnable via a slash command, `/deploy --arg1=val1` or `/variant deploy --arg1=val1`.

Would providing a built-in variant sub-command for starting a slack bot adapter that is able to execute variant tasks would be feasible and beneficial?

```console
$ variant proxy
```

```yaml
authentication:
# ...

authorization:
# ...

channels:
- type: slackbot
  channel: CHANNEL_ID
  token: SLACK_TOKEN
  name: SLACK_BOT_NAME
```
