### ISSUE TITLE
ERRO[0000] open .test.shenv: no such file or directory 

### ISSUE THREAD

**Issue by osterman** [mumoshu/variant#38]
## what
* Move message to `DEBUG` level

## why
* Env files should be optional 
* Multiple interfaces exist for passing envs
* Message is alarming, but nothing to fear =)

## example

```
#!/usr/bin/env variant

tasks:
  ls:
    script: |
      ls -l 

  foo:
    parameters:
    - name: bar
      type: string
      description: "the bar"
    - name: environment
      type: string
    script: |
      echo "Hello {{ get "bar" }} you are in the {{ get "environment" }}
```
