### ISSUE TITLE
Clear separation of parameters vs options

### ISSUE THREAD

**Issue by mumoshu** [mumoshu/variant#4]
variant doesn't differentiate those two today. So given the example below:

```
deploy:
  inputs:
  - name: target
  - name: mysql.host
  script: |
    echo deploy"(mysql_host={{.mysql.host}})"
    echo {{.target}}
    echo err message 1>&2
    echo {{.env}}
```

Both `variant deploy $target $mysql_host` and `variant deploy --target $target --mysql-host $mysql_host` are valid to variant. However, how this kind of flexibility is justified?

For the sake of clariness, we should be able to write:

```
deploy:
  parameters:
  - name: target
  options:
  - name: mysql.host
  script: |
    # snip
```

so that only `variant deploy $target --mysql-host $mysql_host` is valid.
