### ISSUE TITLE
feat: automatic retries

### ISSUE THREAD

**Issue by mumoshu** [mumoshu/variant#47]
Adding exponential retries to unreliable commands is a common pattern to make your task reliable accomplished. You may have been using a bash loop or a dedicated command for implementation.

How about `variant` having the feature out of the box?

```yaml
tasks:
  foo:
    retry:
      limit: 5
      timeout: 10m
      backoff: lin:500ms
    script: |
      ./my_unreliable_cmd whatever
```

**Comment by osterman** [comment]
I'm on the fence. On the one side, I like it because it simplifies a common pattern as you mention. On the other, it might be adding too much to variant? It's hard to draw the line. For example, in the `script` section, we might want to retry one command and not the other, rather than retry the entire script. However, if we want to retry the entire `script` section, then we do need a `retry` block.

I like composing commands, but sometimes I can take it too far.

An extreme mock example of chaining commands:
```
exec dumb-init gosu ${ATLANTIS_USER} env BASH_ENV=/etc/direnv/bash direnv exec . chamber exec atlantis -- atlantis server
```

**Comment by mumoshu** [comment]
> On the other, it might be adding too much to variant?

@osterman Might be! Adding too much to variant is problematic in two ways: the size of the variant binary gets bigger, and its complexity increases.

> I like composing commands, but sometimes I can take it too far.

I have the same sentiment as yours here. I can't help wishing variant could be enhanced somehow saves us the issues arises when you compose commands.

> ```
> exec dumb-init gosu ${ATLANTIS_USER} env BASH_ENV=/etc/direnv/bash direnv exec . chamber exec atlantis -- atlantis server
> ```

Just a quick idea but what if variant adds some config keys to abstract away concrete commands in favor of what you want to achieve in the script? So that the above becomes:

```yaml
tasks:
  atlantis:
    tasks:
      server:
        envFrom:
          chamber: atlantis
        env:
          BASH_ENV: /etc/direnv/bash
        user: '{{ env "ATLANTIS_USER" }}'
        script: |
          atlantis server
```

```console
exec dumb-init -- ./myapp atlantis server

# variant just transform the script `atlantis server` into:
#   gosu ${ATLANTIS_USER} env BASH_ENV=/etc/direnv/bash direnv exec . chamber exec atlantis -- atlantis server
```

Btw, I tend to cause scope creep on projects so feedbacks like yours are always welcomed. Thanks again for that!
