### ISSUE TITLE
feat: External Tasks & Interfaces

### ISSUE THREAD

**Issue by mumoshu** [mumoshu/variant#5]
`variant` as of today allows us to create a workflow composed of multiple flows:

```
all:
  steps:
  - flow: build
  - flow: push
build:
  script: |
    # snip
push:
  script: |
    # snip
```

`variant all` results in `variant build` followed by `variant push`.

I have an idea to extend this to be able to support external flows. External flows are loaded from the variant file specified by `source:`:

```
steps:
- flow: build
   source: '{{ get "path" }}/variant.yaml'
```
