### ISSUE TITLE
Reusing only part(s) of scripts

### ISSUE THREAD

**Issue by mumoshu** [mumoshu/variant#53]
I tend to organize my variant scripts to the "header" and the "body" like seen in the following example:

```
    script: |
      # header
      {{ $env    := get "environment" }}
      {{ $state  := merge (get $env) (get "file" | readFile | fromYaml) }}
      {{ $name   := $state | dig "name" }}
      {{ $bucket := get "bucket" }}
      {{ $ns     := $state | dig "namespace" }}

      # body
      cat <<EOF > state.yaml
      {{ $state | toYaml }}
      EOF

      aws s3 cp state.yaml s3://{{ $bucket }}/eks/environments/{{ $env }}/namespaces/{{ $ns }}/{{ $name }}/state.yaml 
```

What if you want to reuse the "header` in various variant scripts, to that you can tidy up your variant command for more focus on the "body"s of it? There's no way atm.

I propose to extend `script:` to optionally accept an array, so that you can use YAML anchors for reusing headers:

```yaml
mixins:
  header: &header
      {{ $env    := get "environment" }}
      {{ $state  := merge (get $env) (get "file" | readFile | fromYaml) }}
      {{ $name   := $state | dig "name" }}
      {{ $bucket := get "bucket" }}
      {{ $ns     := $state | dig "namespace" }}

tasks:
  foo:
    parameters:
    # ....
    script:
    - *header
    - |
      cat <<EOF > state.yaml
      {{ $state | toYaml }}
      EOF

      # ...
```
