### ISSUE TITLE
Dependency Management(Versioned Directories)

### ISSUE THREAD

**Issue by mumoshu** [mumoshu/variant#56]
variant should provide a generic way to manage dependencies of your variant command:

```yaml
dependent:
  directories:
  - path: ./helmfile-libs/stable
     # multiple library helmfile.yaml files should be maintained at `stable/*/helmfile.yaml`
     source: github.com/myorg/helmfile-libs?ref=v0.9.0//stable

tasks:
   sync:
     script: |
       # Now that variant populated ./helmfile-libs/stable/*.helmfile.yaml and their assets
       # You can sync with a local helmfile.yaml, that depends on external, versioned "library" sub-helmfiles
       helmfile sync
```

## Rationale

#51 and #52 made it possible for variant to import a variant command or a parameter value from various sources like github.

For importing a variant command, this works as long as the imported command doesn't have extra dependencies to assets that resides within the same repository. For example, the imported command breaks if it depended on `hack/myhelper` in the remote repository.

One more thing to consider would be to how you can import a set of files, not a single remote config/command file, that is necessary to make your variant command work.

You need to use git-submodules or a hand-made script that calls other commands interacting with various sources to fully address it today.

**Comment by osterman** [comment]
Is this kind of like `.terraform/modules/<id>`?

**Comment by mumoshu** [comment]
@osterman Mostly. It's like `.variant/<source id>` as implemented in #51 and #52, for example `.variant/github_com_mumoshu_kodedeploy_ref=mycommitid`, so that references to subsets of the same source can share the same source-cache.

**Comment by mumoshu** [comment]
Trying to learn from terraform modules. My understanding is that terraform modules has a more strict interface than the variant's "dependent directories".

variant can ensure a specific local directory at `path` to the specific version of the (sub)directory stored in the go-gettable source. The only interface requirements are that it is a directory, and is stored in a go-gettable source, at the moment.

**Comment by osterman** [comment]
> `.variant/github_com_mumoshu_kodedeploy_ref=mycommitid`

This is nice. I hate the terraform obfuscated ids.

**Comment by mumoshu** [comment]
Note that `path: ./helmfile-libs/stable` should be relative to the variant command containing the `dependent.directories` directive, not the variant command called by the user.

For example, running `path/to/parentcmd` in the below example should populate `path/to/mylibs/communitylibs`, so that ` parentcmd foo` works because `foo`'s dependencies are correctly loaded into the directory `foo` resides in.

`parentcmd`:

```yaml
dependent:
  directories:
  - path: mylibs
    source: src/spec/to/mylibs

tasks:
  foo:
    import: ./mylibs/foo
```

`mylibs/foo`:

```yaml
dependent:
  directories
  - path: communitylibs
     source: src/spec/to/communitylibs

tasks:
  # ...
```

**Comment by mumoshu** [comment]
Also we should have a easy way to get the absolute path to the currently-running variant command, so that we can distinguish the imported command referenced something under the current working directory vs one of dependencies:

`mylibs/foo`:

```yaml
dependent:
  directories
  - path: communitylibs
     source: src/spec/to/communitylibs

tasks:
  run:
    script: |
      # runs path/to/something
      ./something
     # runs path/to/mylibs/something
     # {{ .dir }} returns path/to/mylibs because this command is located at path/to/mylibs/foo
     {{ .dir }}/something
```
