### ISSUE TITLE
Experimental: Dependency Management(Packages)

### ISSUE THREAD

**Issue by mumoshu** [mumoshu/variant#57]
> This is even more experimental than other features :)

variant should be able to manage package (direct) dependencies of your variant command, along with those of imported commands(=transitive dependencies):

`yourcmd`:

```yaml
dependent:
  commands:
  - command: terraform
    version: "=0.11.11"
    #logically translated to:
    #provider: { apk: { version: "=0.11.11"} }

tasks:
  kopsctl:
    import: src/spec/to/kopsctl
```

`kopsctl`:

```yaml
dependent:
  commands:
  - command: kops
    version: "<1.2.3-suffix"
    #logically translated to:
    #provider: { apk: { version: "<1.2.3-suffix"} }

# ...
```

Running `./yourcmd gen-dockerfile` should produce:

```
ADD yourcmd /usr/local/bin/yourcmd
RUN mkdir /work
ENV PATH $PATH:/usr/local/bin
WORKDIR /work
# Install the cloudposse alpine repository
ADD https://apk.cloudposse.com/ops@cloudposse.com.rsa.pub /etc/apk/keys/
RUN echo "@cloudposse https://apk.cloudposse.com/3.8/vendor" >> /etc/apk/repositories
# Install all the direct and transitive dependencies
RUN apk add --no-cache --update terraform=0.11.11 kops=<1.2.3-suffix
CMD [ "yourcmd" ]
```

So that you can easily build a bundle of your `yourcmd`.

## Rationale

I want to distribute my complex variant command for running inside any container orchestration system and any container-based CI services like CircleCI and Codefresh.
