### ISSUE TITLE
Run subtask over filtered items

### ISSUE THREAD

**Issue by mumoshu** [mumoshu/variant#7]
The idea is to introduce a new parameter type`array` with `delimiter`. The two populates the `items` along with the `filter` in order to select the subset of the items contained in the parameter value:

```yaml
parameters:
- name: changed-files
  type: array
  delimiter: newline
steps:
-  items: changed-files
    filter: { "path.match": "playbooks/*.yml" }
    flow: mysubtask
    arguments:
      target-filepath: '{{ .item }}'
```
