### ISSUE TITLE
doc: Multi-step Task

### ISSUE THREAD

**Issue by mumoshu** [mumoshu/variant#70]
The doc currently explain only `script` under the task definition that runs a single bash script.

Variant actually support multi-step tasks, that is able to run multiple scripts, or even tasks like this:

```yaml
tasks:
  foo:
    steps:
    - task: anothertask
    - script: |
         echo hello world
```
