### ISSUE TITLE
doc: Run an interactive command

### ISSUE THREAD

**Issue by mumoshu** [mumoshu/variant#71]
Variant supports `interactive: true` that connects STDIN to the script runner, which is usually a bash process. (We do support not only bash but any script runner but that's an another story!)

So the below fails because vi is unable to find tty:

```yaml
tasks:
  edit:
    script: |
       vi
```

But this succeeds due to the reason explained above:

```yaml
tasks:
  edit:
    interactive: true
    script: |
      vi
```
