### ISSUE TITLE
feat: default commands

### ISSUE THREAD

**Issue by mumoshu** [mumoshu/variant#85]
Extracted from our official slack channel:

> have you considered a "default" command? e.g. if none of the args match, pass `$*` to some command (edited) 
> 
> e.g. `terraformctl` would intercept any task defined, but if not defined, it would pass to `terraform`
> basically, using `variant` to overload commands

I'd start this by just allowing `name` of each task to be omitted.

That is, assuming we have a variant command like the below:

```yaml
tasks:
- name: foo
   # ...
   script: |
     # whatever..
- script: |
     echo -- {{ .args }}
```

Running it with `./yourcmd bar --baz` results in running `echo -- bar --baz`.
