### ISSUE TITLE
improvement: Allow "autoenv" parameters to be processed on the  task level

### ISSUE THREAD

**Issue by aroq** [mumoshu/variant#94]
## what

Process ```autoenv``` on the ```task``` level instead of the ```step script``` level only.

## why

To allow processing ```autoenv``` parameters in every type of steps, e.g. make it visible in "called" tasks (```step-tasks```), like in the example below.

With this improvement, the following script will echo "test_value" when ```test``` task will be executed.

```
tasks:
  test:
    autoenv: true
    parameters:
    - name: param1
      type: string
      default: test_value
    steps:
    - task: exec

  exec:
    script: |
      echo ${PARAM1}

```
